/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NeoExpressFile {
  magic: number;
  "address-version": number;
  "consensus-nodes": [NeoExpressConsensusNode, ...NeoExpressConsensusNode[]];
  wallets?: NeoExpressWallet[];
  settings?: {
    [k: string]: unknown;
  };
}
export interface NeoExpressConsensusNode {
  "tcp-port": number;
  "ws-port": number;
  "rpc-port": number;
  wallet: NeoExpressWallet;
}
export interface NeoExpressWallet {
  name: string;
  accounts: NeoExpressAccount[];
}
export interface NeoExpressAccount {
  "private-key": string;
  "script-hash"?: string;
  label?: null | string;
  "is-default"?: boolean;
  contract?: {
    script: string;
    parameters: string[];
  };
}
