/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NeoInvokeFile = InvokeOperation | [InvokeOperation, ...InvokeOperation[]];
export type ContractParameter = null | boolean | number | string | ContractParameter[] | TypedContractParameter;
export type TypedContractParameter =
  | {
      type: "Boolean";
      value: boolean;
    }
  | {
      type: "ByteArray" | "Hash160" | "Hash256" | "Integer" | "PublicKey" | "Signature" | "String";
      value: string;
    }
  | {
      type: "Array";
      value: ContractParameter[];
    }
  | {
      type: "Map";
      value: {
        key: ContractParameter;
        value: ContractParameter;
      }[];
    };

export interface InvokeOperation {
  contract: string;
  operation: string;
  args?: ContractParameter[];
}
